on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run tests on commits
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call the test action
        uses: . # Uses an action in this
        id: hello
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
