name: Run docker
on:
  workflow_dispatch:
    inputs:
      terms:
        description: 'Search Terms'
        required: false
        default: 'automatic,docker'
      mark:
        description: 'Testing Mark'
        required: false
        default: 'search_test_v3'

jobs:
  testing_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    name: Run tests on pushes
    env:
      SEARCH_TERMS: ${{ github.event.inputs.terms }}
    steps:
      - name: Run tests
        uses: docker://gqassurance/tm21:latest
        with:
          args: -m search_test_v3
