name: Run tests in published docker image
on:
  workflow_dispatch:
    inputs:
      terms:
        description: 'Search Terms'
        required: false
        default: 'published,docker'
      mark:
        description: 'Testing Mark'
        required: false
        default: 'dockerized'

jobs:
  testing_job:
    runs-on: ubuntu-latest
    env:
      SEARCH_TERMS: ${{ github.event.inputs.terms }}
    steps:
      - name: Run tests
        uses: docker://gqassurance/tm21:latest
        with:
          args: -m ${{ github.event.inputs.mark }}
