name: Run tests every push

on: [push]

jobs:
  testing_job:
    runs-on: ubuntu-latest
    name: Run tests on pushes
    env:
      SEARCH_TERMS: push,testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t tm21 .
      - name: Run docker image
        run: docker run -e SEARCH_TERMS -e BASE_URL tm21 "-m dockerized"
